FROM gentoo/stage3-amd64:20200225
VOLUME ["/var/db/repos/gentoo", " /var/cache/binpkgs ", "/var/cache/distfiles"]
ADD gentoo.conf /etc/portage/repos.conf/gentoo.conf
ADD make.conf /etc/portage/make.conf
